export { default as CreatePost } from "./CreatePost";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as GetSinglePost } from "./GetSinglePost";
export { default as Login } from "./Login";
export { default as MyPosts } from "./MyPosts";
export { default as Page404 } from "./Page404";
export { default as Profile } from "./Profile";
export { default as Register } from "./Register";
export { default as HomePage } from "./HomePage";
